### ISSUE TITLE
Need to go through and make sure sensitive data isn't being pushed

### ISSUE THREAD

**Issue by veb** [vebnz/oddit#120]
Like fixtures.json for example as it would have API Keys and such.

We'll need to go back through our commits and kill the ones where we've pushed accidental data.

**Comment by veb** [comment]
I had a look at https://help.github.com/articles/remove-sensitive-data/

Which led me to https://rtyley.github.io/bfg-repo-cleaner/ but seems to need java. PFFT

**Comment by veb** [comment]
@avwave is it worth installing Java just for this?

**Comment by Kingy** [comment]
I did a rebase on the old commit and took out all the sensitive data. The fixtures.json file might be corrupt now so probably can't be loaded but I don't think that matters considering we're making a new one for ourselves and a dummy one for others.

I will let @veb confirm before closing

**Comment by avwave** [comment]
nixed the fixtures.json from history.  lucky i have bfg-repo-cleaner handy.

everyone clone a fresh repo though
