### ISSUE TITLE
Need to limit the job titles

### ISSUE THREAD

**Issue by veb** [vebnz/oddit#95]
Need to limit the job titles

**Comment by Kingy** [comment]
To how many chars? Or no limit, but only show X on the job lists "We want a web devel..."

**Comment by veb** [comment]
![image](https://cloud.githubusercontent.com/assets/376245/17504998/f65f247a-5e51-11e6-9fa8-44fb663807b6.png)

See any bigger it'll look shit... we may want to ask @avwave about changing the style to make the listings longer and remove the sidebar?
