### ISSUE TITLE
The logo is weird.

### ISSUE THREAD

**Issue by veb** [vebnz/oddit#98]
[16:25:25]  <+Logicgate>    The logo is weird.

**Comment by avwave** [comment]
still selecting from a few drummed up
![odditx-10](https://cloud.githubusercontent.com/assets/310340/17534712/1b879762-5ebd-11e6-8ee7-e54c946933f4.png)

going with 8th one for now

**Comment by Kingy** [comment]
Current design is perfect (8th on the list above)
